import json

def generate_patch(baseline_path, output="drift_patch.py"):
    with open(baseline_path) as f:
        base = json.load(f)

    det = base.get("determinism", {})

    code = f"""
# Auto-generated by drift-debugger
import torch
import random
import numpy as np
import os

def apply_patch():
    torch.backends.cuda.matmul.allow_tf32 = {det.get("tf32_allowed", False)}
    torch.backends.cudnn.deterministic = {det.get("cudnn_deterministic", True)}
    torch.backends.cudnn.benchmark = {det.get("cudnn_benchmark", False)}

    try:
        torch.use_deterministic_algorithms(True)
        os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
    except:
        pass

    seed = {det.get("seed", 42)}
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    print("✅ Drift patch applied")

apply_patch()
"""

    with open(output, "w") as f:
        f.write(code)

    print(f"🛠️ Patch generated: {output}")
